IvarsSykkelsjappe/IvarsSykkelsjappe/Controllers/BikesController.cs
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using IvarsSykkelsjappe.Models.Bikes;
using IvarsSykkelsjappe.Services.Bikes;
using IvarsSykkelsjappe.Services.Messaging;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IvarsSykkelsjappe.Controllers
{
    using static WebConstants;

    public class BikesController : Controller
    {
        private readonly IBikeService bikeService;
        private readonly IMapper mapper;
        private readonly IEmailSender emailSender;

        public BikesController(IBikeService bikeService, IMapper mapper, IEmailSender emailSender)
        {
            this.bikeService = bikeService;
            this.mapper = mapper;
            this.emailSender = emailSender;
        }

        //[Authorize]
        //[Authorize(Roles = "Admin")]
        //public IActionResult AllAdmin()
        //{
        //    var bikes = this.bikeService.GetAll();
        //    return View(bikes);
        //}

        //[Authorize]
        //[Authorize(Roles = "Admin")]
        //public IActionResult Edit(int id)
        //{
        //    if (!User.IsInRole("Admin"))
        //    {
        //        return Unauthorized();
        //    }

        //    var bike = this.bikeService.GetEdit(id);

        //    var bikeForm = this.mapper.Map<BikeFormModel>(bike);

        //    bikeForm.Categories = this.bikeService.GetBikeCategories();

        //    return View(bikeForm);

        //    //without AutoMapper
        //    //return View(new BikeFormModel
        //    //{
        //    //    Brand = bike.Brand,
        //    //    Model = bike.Model,
        //    //    Description = bike.Description,
        //    //    Price = bike.Price,
        //    //    ImageUrl = bike.ImageUrl,
        //    //    Year = bike.Year,
        //    //    BikeCategoryId = bike.BikeCategoryId,
        //    //    Categories = this.bikeService.GetBikeCategories()
        //    //});
        //}

        //[Authorize]
        //[HttpPost]
        //[Authorize(Roles = "Admin")]
        //public IActionResult Edit(BikeFormModel bikeModel, int id)
        //{

        //    if (!ModelState.IsValid)
        //    {
        //        bikeModel.Categories = this.bikeService.GetBikeCategories();
        //        return View(bikeModel);
        //    }

        //    this.bikeService.Edit(bikeModel, id);
        //    return RedirectToAction(nameof(AllCustomer));
        //}

        [Authorize(Roles = "Admin, User, Mechanic")]
        public IActionResult AllCustomer(AllBikesQueryModel queryModel)
        {
            this.bikeService.AllSearch(queryModel);
            return View(queryModel);
        }

        //[Authorize]
        //[Authorize(Roles = "Admin")]
        //public IActionResult Create()
        //{
        //    return View(new BikeFormModel
        //    {
        //        Categories = this.bikeService.GetBikeCategories()
        //    });
        //}


        //[HttpPost]
        //[Authorize]
        //[Authorize(Roles = "Admin")]
        //public IActionResult Create(BikeFormModel bikeForm)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        bikeForm.Categories = this.bikeService.GetBikeCategories();
        //        return View(bikeForm);
        //    }

        //    this.bikeService.Add(bikeForm);
        //    return RedirectToAction(nameof(AllCustomer));
        //}

        [Authorize]
        public IActionResult Details(int id)
        {
            var bike = this.bikeService.GetDetails(id);
            return View(bike);
        }

        //[Authorize]
        //[Authorize(Roles = "Admin")]
        //public IActionResult Delete(int id)
        //{
        //    this.bikeService.Delete(id);
        //    return RedirectToAction(nameof(AllAdmin));
        //}

        [HttpPost]
        [Authorize(Roles = "User")]
        public async Task<IActionResult> SendToEmail(int id)
        {
            var bike = this.bikeService.SendBikeByEmail(id);
            var html = new StringBuilder();
            html.AppendLine($"<h1>{bike.Brand}</h1>");
            html.AppendLine($"<h3>{bike.Model}</h3>");
            //html.AppendLine($"<img src=\"{bike.ImageUrl}\" />");
            await this.emailSender.SendEmailAsync("info@ivarssykkelsjappe.no", "IvarsSykkelsjappe", "namari6705@bubblybank.com", bike.Brand, html.ToString());
            TempData[GlobalMessageKey] = "The email was sent successfully.";
            return this.RedirectToAction(nameof(this.Details), new { id });
        }
    }
}

IvarsSykkelsjappe/IvarsSykkelsjappe/Controllers/PopUpsController.cs
using Microsoft.AspNetCore.Mvc;

namespace IvarsSykkelsjappe.Controllers
{
    public class PopUpsController : Controller
    {
        public PopUpsController()
        {

        }

        public IActionResult Location()
        {
            return View();
        }
    }
}

IvarsSykkelsjappe/IvarsSykkelsjappe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] @WebConstants.SystemSlogan</title>
    <meta name="description" content="Tired of mass produced bikes with no identity? We set out to create some bicycle all-stars, loaded with character. Each of our custom bicycles has a unique story - just like you">
    <meta name="keywords" content="Bicycle repair, bicycle services, bicycle shop, bicycle popup, book repair">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="/images/IvarsLogo.png" class="rounded-circle" width="50" height="50">
                    IvarsSykkelsjappe
                </a>
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Chat">Chat</a>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated && User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bikes" asp-action="AllCustomer">Our Bikes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bookings" asp-action="BookTime">Booking</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bookings" asp-action="MyBookings">My Bookings</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PopUps" asp-action="Location">Pop-Ups</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AboutUs">About Us</a>
                            </li>
                        }
                        else if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle text-dark" data-toggle="dropdown">Bikes</a>
                                <div class="dropdown-menu">
                                    <div class="dropdown-divider"></div>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Bikes" asp-action="Create">Create Bike</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Bikes" asp-action="All">Admin Bikes</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Bikes" asp-action="AllCustomer">Our Bikes</a>
                                    <div class="dropdown-divider"></div>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle text-dark" data-toggle="dropdown">Bookings</a>
                                <div class="dropdown-menu">
                                    <div class="dropdown-divider"></div>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Bookings" asp-action="BookTime">Create Booking</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Bookings" asp-action="AllBookings">All Bookings</a>
                                    <div class="dropdown-divider"></div>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle text-dark" data-toggle="dropdown">Services</a>
                                <div class="dropdown-menu">
                                    <div class="dropdown-divider"></div>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Assistances" asp-action="Create">Create Service</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Assistances" asp-action="AllAssistances">All Services</a>
                                    <div class="dropdown-divider"></div>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle text-dark" data-toggle="dropdown">Parts</a>
                                <div class="dropdown-menu">
                                    <div class="dropdown-divider"></div>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Products" asp-action="Create">Create Part</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Products" asp-action="AllProducts">All Parts</a>
                                    <div class="dropdown-divider"></div>
                                </div>
                            </li>
                            @*<li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Bookings" asp-action="BookTime">Booking</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Bookings" asp-action="AllBookings">All Bookings</a>
                                </li>*@
                            @*<li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Bikes" asp-action="Create">Create Bike</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Bikes" asp-action="All">Admin Bikes</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Bikes" asp-action="AllCustomer">Our Bikes</a>
                                </li>*@
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PopUps" asp-action="Location">Pop-Ups</a>
                            </li>
                        }
                        else if (User.Identity.IsAuthenticated && User.IsInRole("Mechanic"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bookings" asp-action="AllBookingsForToday">All Bookings</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bookings" asp-action="MyOrders">My Orders</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PopUps" asp-action="Location">Pop-Ups</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bikes" asp-action="AllCustomer">Our Bikes</a>
                            </li>
                        }

                        <a class="nav-link" href="https://www.instagram.com/ivarssykkelsjappe/?hl=en"><i class="fa fa-instagram"></i></a>
                        <a class="nav-link" href="https://www.facebook.com/sykkelsjappe/"><i class="fa fa-facebook"></i></a>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @if (TempData.ContainsKey(WebConstants.GlobalMessageKey))
            {
                <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
                    <span type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span>
                    @TempData[WebConstants.GlobalMessageKey]
                </div>
            }
            @RenderBody()
        </main>
    </div>

    @*<div class="container">
        <main role="main" class="pb-3">
            @if (TempData.ContainsKey(WebConstants.GlobalMessageKey))
            {
                <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
                    <span type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span>
                    @TempData[WebConstants.GlobalMessageKey]
                </div>
            }
            @RenderBody()
        </main>
    </div>*@

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - @WebConstants.SystemName - <a asp-area="" asp-controller="Bookings" asp-action="BookTime">Book time at the workshop</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/signalr/dist/browser/signalr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>